# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build MultiChat

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8

      - name: Build with Maven
        run: mvn -B package --file multichat/pom.xml

      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@master
        with:
          name: MultiChat plugin jars
          path: |
            multichat/target/*.jar
            !multichat/target/original*
